name: CaloIslands
version: 0.2.0-SNAPSHOT
main: me.calo.islands.CaloIslandsPlugin
api-version: '1.21'
author: calo
description: Sistema de islas, aldeas, bosses y eventos PvE de GoldenLyons.
commands:
  caloislands:
    description: Comando principal de CaloIslands.
    usage: /caloislands
    aliases: [ci]
    permission: caloislands.admin
permissions:
  caloislands.admin:
    default: op
softdepend: [MythicMobs]
